SELECT * FROM accessRole;

INSERT INTO baseType VALUES('ACCESSROLE_INACT','STATUS_ACCESSROLE','Inactivo',NULL,NULL);
INSERT INTO baseType VALUES('ACCESSROLE_ACT','STATUS_ACCESSROLE','Activo',NULL,NULL);


INSERT INTO accessRole VALUES(1,1,1,'ACCESSROLE_ACT');